name: Cypress Tests

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

env:
    CONFIG_PATH: tests/data/config

jobs:
    cypress-run:
        runs-on: sirius
        timeout-minutes: 10

        steps:
            - name: Checkout
              uses: actions/checkout@v2
            # Install NPM dependencies, cache them correctly
            # and run all Cypress tests
            - name: check env
              run: echo ${CONFIG_PATH}
            - name: Install packages
              run: |
                  sudo apt-get update
                  sudo apt install -y docker-compose
            - name: Deploy containers & load data
              run: |
                  sudo docker-compose -f docker-compose.test.yaml up -d
                  sleep 1m
                  bash tests/load_data.sh
                  sleep 30s
            - name: Build mainapp
              working-directory: ./mainapp
              run: node & npm ci && npm run build
            - name: Cypress run
              uses: cypress-io/github-action@v4
              with:
                  start: npm start
                  wait-on: "http://localhost:3011"
                  wait-on-timeout: 120
                  config-file: cypress.config.ts
                  headless: true
                  browser: chromium
                  spec: |
                      cypress/e2e/browser.cy.js
                      cypress/e2e/genealogy.cy.js
                      cypress/e2e/kgmapping.cy.js
                      cypress/e2e/login.cy.js
                      cypress/e2e/sparql_endpoint.cy.js
                      cypress/e2e/standardizer.cy.js
                      cypress/e2e/ConfigEditor.cy.js
                      cypress/e2e/KGbrowser.cy.js
                      cypress/e2e/lineage.cy.js
                      cypress/e2e/match.cy.js
                      cypress/e2e/SQLquery.cy.js
                  runTests: true
    cleanup:
        runs-on: sirius
        needs: cypress-run
        steps:
            - name: Cleanup
              run: sudo docker-compose -f docker-compose.test.yaml down
